# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b50237a88c402036bfddecc6b11d2b38a5e1097a2e0223bd1572a20bd915390cbc1eb8ce60446136e6abd165c7f0390007cce65702edc8940f98a695483660cf

test:
  secret_key_base: d9c226a06f3269503684963ac341958141808d8a8267a75ad2b372f308e9523888912abc79d189ba4312e2624e6a6ed9318e5982383395328676789d546c2cf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
